### ISSUE TITLE
Firebase config shouldn't be public or has to be restricted?

### ISSUE THREAD

**Issue by miki-tebe** [studytme/studytme-website#15]
i think this shouldn't be public
![image](https://user-images.githubusercontent.com/26773624/172460737-2f21a2f8-0684-4525-849b-c0520dc69d3a.png)

**Comment by miki-tebe** [comment]
https://cloud.google.com/docs/authentication/api-keys#securing_an_api_key

**Comment by n3oAlex** [comment]
Thanks for noticing! ❤️  The API key is restricted only to one Google API and scoped only to studytme.com. There are also strict rules set for firestore access. 

Firebase config is a public information as it can be read by each client from the source code. For easier co-operation with more junior devs and G I decided to keep it in source control. 

If you have more experience with github actions and can do a pull request on having the config values stored in github secrets and auto inserted on job run I would love that ❤️

**Comment by miki-tebe** [comment]
That will work :+1: and makes sense. I don't have any experience with GitHub actions sorry.

Feel free to close this issue.
